# Generated by Django 4.2.7 on 2025-02-19 16:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='Заголовок')),
                ('title_ky', models.CharField(max_length=100, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Заголовок')),
                ('title_tr', models.CharField(max_length=100, null=True, verbose_name='Заголовок')),
                ('title_ar', models.CharField(max_length=100, null=True, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_en', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_tr', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_ar', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('phone_number_ru', models.CharField(max_length=30, null=True, verbose_name='Номер телефона')),
                ('phone_number_ky', models.CharField(max_length=30, null=True, verbose_name='Номер телефона')),
                ('phone_number_en', models.CharField(max_length=30, null=True, verbose_name='Номер телефона')),
                ('phone_number_tr', models.CharField(max_length=30, null=True, verbose_name='Номер телефона')),
                ('phone_number_ar', models.CharField(max_length=30, null=True, verbose_name='Номер телефона')),
                ('adress', models.CharField(max_length=50, verbose_name='Адрес')),
                ('adress_ru', models.CharField(max_length=50, null=True, verbose_name='Адрес')),
                ('adress_ky', models.CharField(max_length=50, null=True, verbose_name='Адрес')),
                ('adress_en', models.CharField(max_length=50, null=True, verbose_name='Адрес')),
                ('adress_tr', models.CharField(max_length=50, null=True, verbose_name='Адрес')),
                ('adress_ar', models.CharField(max_length=50, null=True, verbose_name='Адрес')),
                ('operating_mode', models.CharField(max_length=100, verbose_name='Режим работы')),
                ('operating_mode_ru', models.CharField(max_length=100, null=True, verbose_name='Режим работы')),
                ('operating_mode_ky', models.CharField(max_length=100, null=True, verbose_name='Режим работы')),
                ('operating_mode_en', models.CharField(max_length=100, null=True, verbose_name='Режим работы')),
                ('operating_mode_tr', models.CharField(max_length=100, null=True, verbose_name='Режим работы')),
                ('operating_mode_ar', models.CharField(max_length=100, null=True, verbose_name='Режим работы')),
                ('link_map', models.URLField(verbose_name='Ссылка на карту')),
                ('link_map_ru', models.URLField(null=True, verbose_name='Ссылка на карту')),
                ('link_map_ky', models.URLField(null=True, verbose_name='Ссылка на карту')),
                ('link_map_en', models.URLField(null=True, verbose_name='Ссылка на карту')),
                ('link_map_tr', models.URLField(null=True, verbose_name='Ссылка на карту')),
                ('link_map_ar', models.URLField(null=True, verbose_name='Ссылка на карту')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
    ]
