# Generated by Django 4.2.7 on 2025-02-19 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AboutAcademy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='link_map_ar',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='link_map_en',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='link_map_ky',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='link_map_ru',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='link_map_tr',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='phone_number_ar',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='phone_number_en',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='phone_number_ky',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='phone_number_ru',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='phone_number_tr',
        ),
    ]
