# Generated by Django 4.2.7 on 2025-02-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutAcademy', '0002_remove_aboutus_link_map_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='link_map_ar',
            field=models.URLField(null=True, verbose_name='Ссылка на карту'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='link_map_en',
            field=models.URLField(null=True, verbose_name='Ссылка на карту'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='link_map_ky',
            field=models.URLField(null=True, verbose_name='Ссылка на карту'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='link_map_ru',
            field=models.URLField(null=True, verbose_name='Ссылка на карту'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='link_map_tr',
            field=models.URLField(null=True, verbose_name='Ссылка на карту'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='phone_number_ar',
            field=models.CharField(max_length=30, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='phone_number_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='phone_number_ky',
            field=models.CharField(max_length=30, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='phone_number_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='phone_number_tr',
            field=models.CharField(max_length=30, null=True, verbose_name='Номер телефона'),
        ),
    ]
