# Generated by Django 4.2.7 on 2025-02-20 11:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutAcademy', '0003_aboutus_link_map_ar_aboutus_link_map_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='Заголовок')),
                ('title_ky', models.CharField(max_length=100, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Заголовок')),
                ('title_tr', models.CharField(max_length=100, null=True, verbose_name='Заголовок')),
                ('title_ar', models.CharField(max_length=100, null=True, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_en', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_tr', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_ar', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Стратегия развития',
                'verbose_name_plural': 'Стратегии развития',
            },
        ),
    ]
