# Generated by Django 4.2.7 on 2025-02-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutAcademy', '0008_document_file_ar_document_file_en_document_file_ky_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevStrategyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='dev_strategy_photos/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фотогравия стратегии развития',
                'verbose_name_plural': 'Фотогравии стратегии развития',
            },
        ),
    ]
