# Generated by Django 4.2.7 on 2025-02-21 12:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutAcademy', '0009_devstrategyphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='Заголовок')),
                ('title_ky', models.CharField(max_length=100, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Заголовок')),
                ('title_tr', models.CharField(max_length=100, null=True, verbose_name='Заголовок')),
                ('title_ar', models.CharField(max_length=100, null=True, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_en', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_tr', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_ar', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
            },
        ),
        migrations.AlterModelOptions(
            name='devstrategyphoto',
            options={'verbose_name': 'Фотография стратегии развития и достижений', 'verbose_name_plural': 'Фотографии стратегии развития и достижений'},
        ),
        migrations.AlterField(
            model_name='devstrategyphoto',
            name='photo',
            field=models.ImageField(upload_to='dev_strategy_photos/', verbose_name='Фото стратегии разватии и достижений'),
        ),
    ]
