# Generated by Django 4.2.7 on 2025-02-21 12:42

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AboutAcademy', '0010_achievements_alter_devstrategyphoto_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'История',
                'verbose_name_plural': 'Истории',
            },
        ),
        migrations.CreateModel(
            name='HistoryObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='object_history_photos/', verbose_name='Фото объекта истории слайдер')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AboutAcademy.history', verbose_name='Изображение истории слайдер')),
            ],
            options={
                'verbose_name': 'Изображение истории слайдер',
                'verbose_name_plural': 'Изображения истории слайдер',
            },
        ),
    ]
