# Generated by Django 4.2.7 on 2025-02-21 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AboutAcademy', '0012_history_description_ar_history_description_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historyobject',
            old_name='photo',
            new_name='image',
        ),
    ]
