# Generated by Django 4.2.7 on 2025-02-21 13:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutAcademy', '0013_rename_photo_historyobject_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='title_adress',
            field=models.CharField(default=1, max_length=100, verbose_name='Заголовок адреса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_adress_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок адреса'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_adress_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок адреса'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_adress_ky',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок адреса'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_adress_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок адреса'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_adress_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок адреса'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_operating_mode',
            field=models.CharField(default=1, max_length=100, verbose_name='Заголовок режима работы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_operating_mode_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок режима работы'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_operating_mode_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок режима работы'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_operating_mode_ky',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок режима работы'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_operating_mode_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок режима работы'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_operating_mode_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок режима работы'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_phone_number',
            field=models.CharField(default=1, max_length=100, verbose_name='Заголовок номера телефона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_phone_number_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок номера телефона'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_phone_number_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок номера телефона'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_phone_number_ky',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок номера телефона'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_phone_number_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок номера телефона'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_phone_number_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок номера телефона'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='adress',
            field=ckeditor.fields.RichTextField(verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='adress_ar',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='adress_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='adress_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='adress_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='adress_tr',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='operating_mode',
            field=ckeditor.fields.RichTextField(verbose_name='Режим работы'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='operating_mode_ar',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Режим работы'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='operating_mode_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Режим работы'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='operating_mode_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Режим работы'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='operating_mode_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Режим работы'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='operating_mode_tr',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Режим работы'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='phone_number',
            field=ckeditor.fields.RichTextField(verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='phone_number_ar',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='phone_number_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='phone_number_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='phone_number_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='phone_number_tr',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Номер телефона'),
        ),
    ]
