# Generated by Django 4.2.7 on 2025-02-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gellary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='date',
            field=models.CharField(max_length=155, verbose_name='Дата'),
        ),
    ]
